server:
  port: 8088
spring:
  application:
    name: order8082
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: order8082
    prefer-ip-address: true
